name: eventstore
version: 1.3.0
homepage: https://gitlab.com/YoEight/eventstore-hs
tested-with: GHC >= 7.8 && <= 8.6
synopsis: EventStore TCP Client
description: EventStore TCP Client <https://eventstore.org>
license: BSD3
license-file: LICENSE
author: Yorick Laupa
maintainer: yo.eight@gmail.com
copyright: Yorick Laupa
category: Database
git: https://gitlab.com/YoEight/eventstore-hs.git

dependencies:
  - base >=4.7 && <5
  - aeson >=0.8
  - mono-traversable ==1.*
  - connection >=0.2
  - containers
  - dotnet-timespan
  - stm
  - time >=1.4
  - uuid ==1.3.*
  - lifted-base
  - text
  - bytestring
  - semigroups
  - hashable
  - unordered-containers
  - stm-chans
  - stm
  - lifted-async
  - safe-exceptions
  - monad-control
  - exceptions
  - transformers-base
  - safe
  - streaming
  - vector
  - polysemy >= 1.0
  - polysemy-plugin
  - monad-loops

extra-source-files:
  - README.md
  - CHANGELOG.markdown
ghc-options: -O2 -fplugin=Polysemy.Plugin
# GHC >= 8.6
# ghc-options: -O2 -fplugin=Polysemy.Plugin -flate-specialise -fspecialise-aggressively

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - LambdaCase
  - RecordWildCards
  - RankNTypes
  - TemplateHaskell # Only for logging capabilities.
  - QuasiQuotes     # Only for string interpolation.
  - FlexibleContexts
  - MultiParamTypeClasses
  - TypeFamilies
  - ConstraintKinds
  - DataKinds
  - GADTs
  - PolyKinds
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
library:
  source-dirs:  '.'
  exposed-modules:
    - Database.EventStore
    - Database.EventStore.Streaming
    - Database.EventStore.Internal.Test
  dependencies:
    - cereal >=0.4 && <0.6
    - protobuf >=0.2.1.1 && <0.3
    - random ==1.*
    - unordered-containers
    - semigroups >=0.5
    - dns >= 3.0.1
    - array
    - http-client >=0.5
    - mtl
    - fast-logger
    - monad-logger >= 0.3.20
    - clock
    - bifunctors
    - interpolate
    - ekg-core

tests:
  eventstore-tests:
    source-dirs: tests
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - eventstore
      - tasty
      - tasty-hunit
      - tasty-hspec
      - aeson
      - text
      - protobuf
      - cereal
      - uuid
      - fast-logger
      - async
      - file-embed
